[package]
name = "rustwall"
version = "0.1.0"
authors = ["Michal Podhradsky <michal.podhradsky@aggiemail.usu.edu>"]

[dependencies]
#smoltcp = { version = "0.4", default-features = true }
smoltcp = { path = "/home/michal/Workspace/rust_projects/smoltcp", default-features = true, features = ["phy-sel4"] }
xml-rs = "0.7.0"
